# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars' }, { name: "Lord of the Rings' }])
#   Character.create(name: "Luke', movie: movies.first)

Course.create(name: "CS 1260 - Python for Beginners")
Course.create(name: "CS 1280 - Introduction to C++")
Course.create(name: "CS 1300 - Discrete Structures")
Course.create(name: "CS 1400 - Introduction to Programming and Problem Solving")
Course.create(name: "CS 2000 - Special Study for Lower Division Students")
Course.create(name: "CS 2180 - Logic and Computing")
Course.create(name: "CS 2400 - Data Structures and Advanced Programming")
Course.create(name: "CS 2450 - Programming Graphical User Interfaces")
Course.create(name: "CS 2520 - Python for Programmers")
Course.create(name: "CS 2560 - C++ Programming")
Course.create(name: "CS 2600 - Unix and Scripting")
Course.create(name: "CS 2640 - Computer Organization and Assembly Programming")
Course.create(name: "CS 2990 - Special Topics for Lower Division Students")
Course.create(name: "CS 2990A - Special Topics for Lower Division Students Activity")
Course.create(name: "CS 2990L - Special Topics for Lower Division Students Laboratory")
Course.create(name: "CS 3010 - Numerical Methods")
Course.create(name: "CS 3110 - Formal Languages and Automata")
Course.create(name: "CS 3310 - Design and Analysis of Algorithms")
Course.create(name: "CS 3520 - Symbolic Programming")
Course.create(name: "CS 3560 - Object-Oriented Design and Programming")
Course.create(name: "CS 3650 - Computer Architecture")
Course.create(name: "CS 3700 - Parallel Processing")
Course.create(name: "CS 3750 - Computers and Society")
Course.create(name: "CS 3800 - Computer Networks")
Course.create(name: "CS 4000 - Special Study for Upper Division Students")
Course.create(name: "CS 4080 - Concepts of Programming Languages")
Course.create(name: "CS 4110 - Compilers and Interpreters")
Course.create(name: "CS 4200 - Artificial Intelligence")
Course.create(name: "CS 4310 - Operating Systems")
Course.create(name: "CS 4350 - Database Systems")
Course.create(name: "CS 4410 - Internship in Computer Science")
Course.create(name: "CS 4450 - Computer Graphics")
Course.create(name: "CS 4500 - Computability")
Course.create(name: "CS 4600 - Cryptography and Information Security")
Course.create(name: "CS 4610 - Senior Project")
Course.create(name: "CS 4620 - Senior Project")
Course.create(name: "CS 4630 - Undergraduate Seminar")
Course.create(name: "CS 4650 - Big Data Analytics and Cloud Computing")
Course.create(name: "CS 4700 - Game Development")
Course.create(name: "CS 4800 - Software Engineering")
Course.create(name: "CS 4810 - Software Engineering Practice")
Course.create(name: "CS 4900 - Honors")
Course.create(name: "CS 4990 - Special Topics for Upper Division Students")
Course.create(name: "CS 4990A - Special Topics for Upper Division Students Activity")
Course.create(name: "CS 4990L - Special Topics for Upper Division Students Laboratory")
Course.create(name: "CS 5000 - Special Study for Graduate Students")
Course.create(name: "CS 5100 - Computer-Assisted Instruction")
Course.create(name: "CS 5170 - Natural Language Processing")
Course.create(name: "CS 5180 - Information Retrieval")
Course.create(name: "CS 5190 - Computer Vision")
Course.create(name: "CS 5210 - Robotics")
Course.create(name: "CS 5220 - Distributed Intelligence in Robotics")
Course.create(name: "CS 5250 - Advanced Computer Architecture")
Course.create(name: "CS 5300 - Advanced Algorithm Design and Analysis")
Course.create(name: "CS 5310 - Computability and Complexity Theory")
Course.create(name: "CS 5350 - Parallel and Distributed Algorithms")
Course.create(name: "CS 5370 - Scheduling Algorithms")
Course.create(name: "CS 5400 - Topics in Compiler Design")
Course.create(name: "CS 5500 - Advanced Information Security")
Course.create(name: "CS 5550 - Digital Image Processing")
Course.create(name: "CS 5650 - Advanced Computer Networks")
Course.create(name: "CS 5660 - Distributed Computing Systems")
Course.create(name: "CS 5700 - Human Computer Interaction")
Course.create(name: "CS 5750 - Topics in Database Systems")
Course.create(name: "CS 5800 - Advanced Software Engineering")
Course.create(name: "CS 5850 - Software Verification and Validation")
Course.create(name: "CS 5860 - Software Metrics and Models")
Course.create(name: "CS 5990 - Special Topics for Graduate Students")
Course.create(name: "CS 5990A - Special Topics for Graduate Students Activity")
Course.create(name: "CS 5990L - Special Topics for Graduate Students Laboratory")
Course.create(name: "CS 6640 - Graduate Seminar")
Course.create(name: "CS 6910 - Directed Research")
Course.create(name: "CS 6920 - Independent Research")
Course.create(name: "CS 6940 - Master's Thesis Project Research")
Course.create(name: "CS 6950 - Master's Degree Project")
Course.create(name: "CS 6960 - Master's Degree Thesis")
Course.create(name: "CS 6990 - Master's Degree Continuation")